---
title: "SMSS By Laws Revisions: 2024-2025 - DRAFT"
output: 
   html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo = FALSE}
h1, #TOC>ul>li {
  color: #000000;
  font-weight: bold;
}

h2, #TOC>ul>li {
  color: #F56600;
  font-weight: bold;
}

h3, #TOC>ul>li {
  color: #522D80;
  font-weight: bold;
}

h4, #TOC>ul>li {
  color: #F56600;
  font-weight: bold;
}

p {
  font-size: 16px;
  color: #522D80;
}

```

# SCHOOL OF MATHEMATICAL AND STATISTICAL SCIENCES GOVERNANCE DOCUMENT (SCHOOL BYLAWS)

## Article I: Name, Vision, Mission

### Section 1: Name
These Bylaws establish the faculty assembly of the School of Mathematical and Statistical Sciences, hereafter referred to in these bylaws as “the School”. 

### Section 2: Vision and Mission
The School is dedicated to Clemson's overall mission of discovery, learning, and engagement.  

<details>
<summary> __Old Version__ </summary>
This is a new section of the bylaws.  
</details>

<details>
<summary> __Explanation of Changes__ </summary>
This is a new section of the bylaws.  This is a recommended section as the purpose of the Bylaws is to set up the shared governance responsibilities of the School of Mathematical and Statistical Sciences.  It if fitting to start that document with the Name and Scope of the School. This vision/mission statement was taken from the SMSS website.
</details>

***

## Article II: Objective

The objective of the Faculty of Mathematical and Statistical Sciences, referred to as the Faculty, shall be to approve curricula and curricular matters; to consider policies affecting teaching, research and other scholarly activities, welfare, and such other matters as might pertain to common professional goals.

The regulations, policies, and procedures of the College of Science and the Clemson University Faculty Manual shall govern matters not treated in these bylaws. The College of Science Bylaws shall take precedence if they conflict with these bylaws. Provisions in these bylaws that are inconsistent with the Clemson University Faculty Manual are null and void.  

***

## Article III: Membership

### Section 1: Voting Faculty

The voting membership of the School shall be composed of all faculty, as defined by the Constitution of the Faculty of Clemson University, with majority regular appointments in the School, including Associate and Assistant Directors with regular appointments, hereafter referred to in these bylaws as “the Faculty”.  Emeritus faculty with any faculty appointment, other than administrative, in the School shall be members of the Faculty.  Other faculty or academic staff not automatically granted voting membership shall be granted voice, invited to attend meetings of the Faculty, and may be conferred voting membership by majority vote at any duly called meeting of the Faculty.  

<details>
<summary> __Old Version__ </summary>
__Section 1: Voting Faculty__
The Voting Faculty shall consist of all individuals, designated by School personnel records as belonging to the Faculty of the School of Mathematical and Statistical Sciences, who are regular faculty, principal or senior lecturers, as defined in the Faculty Manual, and who are not on unpaid leave. Faculty with joint appointments, who are tenured, tenure-track, or principal / senior lecturers, are voting members in the School if their appointment is at least 51% in the School of Mathematical and Statistical Sciences, or 50% if their appointment in any other department or School is less than 50%. Faculty members who are voting members in the School of Mathematical and Statistical Sciences or the former Department of Mathematical Sciences before November 26, 2018 will continue to be voting members. A faculty member who has voting membership and who leaves the School will regain voting membership upon returning to the School. <br>
__Section 2: Administrative Faculty__
The Administrative Faculty shall consist of the School Director and the Division Leaders. <br>
__Section 3: Associate Faculty__
The Associate Faculty shall consist of all person who do not meet the criteria for voting or administrative Faculty.  
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- Changes to the University Constitution redefined faculty to include those in the lecturer ranks.
- Included Associate and Assistant Directors as voting members (further explanation in Article IV)
- _Note:_ Emeritus faculty __with faculty appointments__ are granted voting status
- _Note:_ any other faculty (not on regular appointment) such as postdocs, temporary lectures, etc. and staff may be granted voting rights.  
- Sections 2 and 3 were deleted as they are no longer needed.  
</details>


***

## Article IV: Administrative Structure

### Section 1: Administrative Council and Director's Advisory Board

For School governance considerations, the Administrative Council of the School shall consist of the School Director, the Associate Directors, and the Assistant Directors.  The Director’s Advisory Board shall consist of the Director and Associate Directors. 

<details>
<summary> __Old Version__ </summary>
For School governance considerations, the administrative committee of the School shall consist of the School Director, the Division Leaders and the Associate Directors. All members of the administrative committee shall be tenured and preferably hold the rank of full professor.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- Clarifying structure of Administrative Council and Director Advisory Board
- Streamlining names of "sub-director" positions
- Decided on "Associate Directors" for Division Leaders and "Assistant Directors" for Undergraduate Studies, Graduate Studies, Curriculum & Instruction, and  Online Degree Programs, etc. The titles are meant to mirror the T/TT structure.  
</details>


### Section 2: Appointment of Associate Directors (Division Leads)

Based on nominations from the faculty of the respective Division and advice from the MSSC, the School Director shall appoint Associate Directors. Each appointment shall be for a three-year term, effective August 15, and such Associate Directors may succeed themselves. 

<details>
<summary> __Old Version__ </summary>
Based on nominations from the faculty of the respective Division and advice from the MSSC, the School Director shall appoint Division Leaders. Each appointment shall be for a three-year term, effective August 15, and such Division Leaders may succeed themselves. If a Division cannot field a leader meeting the criteria in Section 1, then the School Director shall appoint one of the Associate Directors to serve as the Division Leader on a year-by-year basis.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- change to title of "Associate Directors" 
- change to order of sections 
</details>

### Section 3: Director and Associate Directors Duties and Responsibilites

The School Director shall have the duties and responsibilities accorded to the Department Chair in the faculty manual. In addition, the Director shall adhere to the SMSS Policies and Procedures document. Associate Directors shall __assist__ the Director in goal-setting and annual evaluations of the faculty in their respective Division. The School Director shall review and finalize the evaluations. Associate Directors shall make recommendations to the School Director for strengthening impact and strategically advancing the School’s discovery, learning, and engagement missions, including strengthening external support through grants and industry partnerships.

<details>
<summary> __Old Version__ </summary>
The School Director shall have the duties and responsibilities accorded to the Department Chair in the faculty manual. Division Leaders shall assist the Director in goal-setting and annual evaluations of the faculty in their respective Divisions. The School Director shall review and finalize the evaluations. Division Leaders shall make recommendations to the School Director for strengthening impact and strategically advancing the School’s discovery, learning, and engagement missions, including strengthening external support through grants and industry partnerships.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- change to title of "Associate Directors" 
- addition of Policies and Procedure Document
- change to order of sections 
- _Note:_ There is a distinction between __"conducting evaluations"__ and __"assisting in evaluations"__.  If Division Leads are responsible for the evaluation of faculty then a full search needs to be done for those positions AND the Division Leads lose their voting privileges within SMSS.  If Division Leads are assisting in the evaluations but the Director ultimately signs the evaluations then the Director can appoint these positions and they do not lose their voting privileges.  
</details>

### Section 4: Appointment of Assistant Directors

Based on nominations from the Faculty and consultation with the Mathematical and Statistical Sciences Council (MSSC, defined in Article VI), the School Director shall appoint from the Faculty, Assistant Directors.   Each appointment shall be for a three-year term, effective August 15, and such Assistant Directors may succeed themselves.

<details>
<summary> __Old Version__ </summary>
Based on nominations from the Faculty and consultation with the Mathematical and Statistical Sciences Council (MSSC, defined in Article VI), the School Director shall appoint from the Faculty the Associate Director for Instruction, the Associate Director for Undergraduate Studies, and the Associate Director for Graduate Studies. Each appointment shall be for a three-year term, effective August 15, and such associate directors may succeed themselves.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- Naming all "sub-directors", that are not Associate Directors (Division Leads), Assistant Directors
- Specific titles of Assistant Directors will be outlined in the Policies and Procedures Document.
</details>


*** 

## Article V: Officers, Meetings, and Voting for SMSS Faculty Meetings

### Section 1: Officers of SMSS Faculty Meetings

The School Director shall serve as Chairperson, and the Administrative Assistant to the Director as Secretary for meetings of the Faculty. If the School Director is unable to chair a meeting, then they shall designate one of the Associate Directors as the meeting chair. In the absence of the Administrative Assistant to the Director, the meeting chair shall appoint a secretary from the staff or faculty.

<details>
<summary> __Old Version__ </summary>
The School Director shall serve as Chairperson, and the Administrative Assistant to the Director as Secretary for meetings of the Faculty. If the School Director is unable to chair a meeting, then they shall designate one of the Division Leaders as the meeting chair. In the absence of the Administrative Assistant to the Director, the meeting chair shall appoint a secretary from the staff or faculty.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- changing Division Lead to Associate Director
</details>

### Section 2: Frequency of SMSS Faculty Meetings

The School Director shall call at least one meeting of the Faculty in each of the fall and spring semesters and any other meeting at their discretion, or upon a petition of at least 25% of the Voting Faculty. Minutes of each meeting shall be forwarded to the Dean of the College. Minutes of each meeting shall be uploaded to the College of Science Repository.

<details>
<summary> __Old Version__ </summary>
The School Director shall call at least one meeting of the Faculty in each of the long semesters and any other meeting at their discretion, or upon a petition of at least 25% of the Voting Faculty. Minutes of each meeting shall be forwarded to the Dean of the College. 
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- changing "long semesters" to "Fall and Spring" semesters for clarity
</details>

### Section 3: Agenda Items for SMSS Faculty Meetings

Written notification of the agenda for meetings shall be provided to the Faculty at least 24 hours in advance of meetings. Non-agenda items may not come to a vote at a meeting unless 50% of the Voting Faculty is present.

### Section 4: Quorum and Results of Voting in SMSS Faculty Meetings

A quorum for a vote shall consist of the faculty in the SMSS faculty meeting. The result of any vote where there are only two possible outcomes (whether at a meeting, electronically, or otherwise) is determined by a simple majority of the eligible votes cast. In the case of a tie, the motion fails. For votes during meetings, proxy votes count if notice has been sent by a Voting Faculty member to the presiding chair before the meeting authorizing an attending voting faculty member to vote her or his proxy. Guidelines for votes in which there are more than two possible outcomes shall be determined and clearly communicated by the MSSC. Rules in other sections of the bylaws or the TPR or PTR guidelines that govern voting supersede the rules in this section.

<details>
<summary> __Old Version__ </summary>
A quorum for a vote shall consist of 51% of the Voting Faculty. The result of any vote where there are only two possible outcomes (whether at a meeting, electronically, or otherwise) is determined by a simple majority of the eligible votes cast. In the case of a tie, the motion fails. For votes during meetings, proxy votes count if notice has been sent by a Voting Faculty member to the presiding chair before the meeting authorizing an attending voting faculty member to vote her or his proxy. Guidelines for votes in which there are more than two possible outcomes shall be determined and clearly communicated by the MSSC. Rules in other sections of the bylaws or the TPR or PTR guidelines that govern voting supersede the rules in this section.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- Since we conduct electronic voting, it is best to have quorum be "members present" so that a meeting and discussion to occur.  Beyond quorum, in order for a vote to pass a simple majority is needed for votes with 2 outcomes.  
</details>


### Section 5: Voting Procedure for Meetings of all faculty
Voting shall be conducted using electronic voting. All votes cast for any measure shall utilize the same method of casting votes. Voting shall be open 1 hour before any duly called meeting of the faculty and close 48 hour after to the adjournment of the same meeting. The Secretary shall record a teller’s report in the minutes for the next meeting of the Faculty and the School Director shall distribute to the Faculty the results of the vote no later than 7 calendar days after the close of voting.

<details>
<summary> __Explanation of Changes__ </summary>
This is a new section in the bylaws.  Suggested language for schools/departments that conduct their votes by electronically.  
</details>

***

## Article VI: Organization of the Faculty

### Section 1: Organization of Divsions and Sub-faculty

The School is composed of three divisions, hereafter referred to as Divisions in the bylaws, established by the School Director.  All faculty employed by the School shall have an academic appointment in the School. The Divisions within the School are: 

- Mathematics
- Statistics and Operations Research
- Mathematics and Statistics Education

Each division contains multiple sub faculties.  

The Mathematics Division consist of these sub faculties: 

- Algebra and Discrete Mathematics
- Computational Mathematics
- Pure and Applied Analysis.

The Statistics and Operations Research Division consists of these sub faculties:

- Applied Statistics and Data Science
- Operations Research
- Probability and Mathematical Statistics. 

The Mathematics and Statistics Education Division consists of these sub faculties: 

- Mathematics Education
- Statistics Education

<details>
<summary> __Old Version__ </summary>
For purposes of representation on various matters, the Faculty is organized as follows. There are three Divisions: Mathematics, Statistics and Operations Research, and Mathematics and Statistics Education. The Mathematics Division consists of three subfaculties: Algebra and Discrete Mathematics, Computational Mathematics, and Pure and Applied Analysis. The Statistics and Operations Research Division consists of three subfaculties: Applied Statistics and Data Science, Operations Research, and Probability and Mathematical Statistics. The Mathematics and Statistics Education Division consists of two subfaculties: Mathematics Education and Statistics Education.

</details>

<details>
<summary> __Explanation of Changes__ </summary>
- easier to read in bullet points
</details>


### Section 2: Subfaculty Membership

Membership on multiple subfaculties or Divisions is encouraged. However, each faculty member shall designate, in consultation with the Directors, (or have designated by the School Director in the absence of a choice) one of the subfaculties for primary membership and shall be entitled to vote on matters pertaining to sub-faculty representation in School affairs in that sub-faculty only. 

<details>
<summary> __Old Version__ </summary>
Membership on multiple subfaculties or divisions is encouraged. However, each faculty member shall designate (or have designated by the School Director in the absence of a choice) one of the subfaculties for primary membership and shall be entitled to vote on matters pertaining to subfaculty representation in School affairs in that subfaculty only. Special faculty shall have primary membership in one of the subfaculties in the Mathematics and Statistics Education Division.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- removing "Special Faculty" provision
</details>


### Section 3: Sub-faculty Responsibilites

Each subfaculty shall have developmental responsibilities relative to academic matters associated with the subfaculty’s interest area. These may include, but are not limited to, updating course syllabi and catalog descriptions, actively participating in the recruitment of faculty, assisting in the administration of multiple section courses, and promoting research and professional development.

***

## Article VII: The Mathematical and Statistical Sciences Council 

### Section 1: MSSC Duties and Responsibilities

The Mathematical and Statistical Sciences Council (MSSC) shall serve as the standing advisory committee for the School, and in that capacity shall advise the School Director on long-range planning, committee assignments, matters of School and faculty welfare, matters pertaining to new teaching and research appointments within the School and on any and all matters brought to it by the Faculty or the School Director.

### Section 2: Frequency of Meetings for MSSC

The MSSC shall schedule at least three meetings during each of the fall and spring semesters and otherwise as necessary. The School Director shall serve as Chairperson. These meetings are open to the Faculty. Generally, the agenda of the MSSC shall be made available to the Faculty 7 calendar days prior to its meetings. Any member of the Faculty may submit to the School Director, in writing, items for this agenda. The minutes of the MSSC meetings shall be distributed to the Faculty in a timely fashion.

<details>
<summary> __Old Version__ </summary>
The MSSC shall schedule at least three meetings during the long semesters and otherwise as necessary. The School Director shall serve as Chairperson. These meetings are open to the Faculty. Generally, the agenda of the MSSC shall be made available to the Faculty one week prior to its meetings. Any member of the Faculty may submit to the School Director (in writing) items for this agenda. The minutes of the MSSC meetings shall be distributed to the Faculty in a timely fashion.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- Change "long semesters" to "fall and spring semesters"
</details>

### Section 3: Review of MSSC Actions

Any action of the MSSC may be called for review by the entire Faculty at one of the Faculty meetings as specified in Article V.

### Section 4: Membership of MSSC

Each of the subfaculties in the School shall elect, by April 15, a representative to the MSSC, who shall serve a one year renewable term as a voting member of the MSSC. In order to qualify for membership on MSSC a faculty member must be a voting member of the School.  The School Director, the Associate Directors and the Assistant Directors shall be nonvoting members of the MSSC.

<details>
<summary> __Old Version__ </summary>
The Mathematics and Statistics Education Division and each of the subfaculties in the Mathematics and Statistics and Operations Research Divisions shall elect a representative to the MSSC, who shall serve as a voting member of the MSSC. The School Director, the Associate Directors and the Division Leaders shall be nonvoting members of the MSSC.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- Since the rank of lecturer is now part of regular faculty, we recommend the Mathematics and Statistics Education Division have similar representation on MSSC to the other divisions.  
</details>

### Section 5: Policies and Procedures

The SMSS Policies and Procedures Document (PPD) shall be created by the MSSC (or an appointed subcommittee).  Approval and amendments of the PPD shall be made by a 2/3 vote of the MSSC voting members.  

<details>
<summary> __Explanation of Changes__ </summary>
- Section is added to make reference to creation, ammendment, and approval of the Policies and Procedures Document
</details>

***

## Article VIII Committees

The School shall have the following standing committees, in addition to MSSC:

1. Administrative Council
2. Computing Resources Committee
3. Undergraduate Affairs and Curriculum Committee
4. Graduate Affairs and Curriculum Committee
5. Research and Development Committee
6. TPR Committee


Membership on Standing Committees should be chosen by April 15 and shall serve on one year renewable appointments, unless otherwise specified. 

The Director, or the Faculty by majority vote in MSSC, may constitute and charge temporary (ad hoc) committees provided such committees are formally charged during a MSSC meeting and the agenda item includes the specific charge, length of service, and composition. Temporary Committees shall report their activities at each MSSC meeting for the duration of their charge and issue a final report upon completion of the charge or at the conclusion of the term of service. The Director may appoint members, or designate ex-officio voting members, to temporary committees provided that at least a majority of the membership is selected by the MSSC. 

Additional Standing Committees may be added by amendment to these bylaws.



<details>
<summary> __Old Version__ </summary>
The School shall have the following standing committees, in addition to MSSC:

1. Administrative Committee
2. Computing Facilities Committee
3. Undergraduate Affairs Committee
4. Graduate Affairs Committee
5. Curriculum Committee
6. Research and Development Committee
7. Division TPR Committees
8. Lecturer Advisory Committee
9. Post Tenure and Special Faculty Review Committee

Ad hoc and other committees may be appointed by the School Director as needed. Except as specified below, the School Director, with the advice of the MSSC, shall fix the size of all committees and assign their duties; and, with the approval of the MSSC, shall appoint the chairpersons and members. The Curriculum Committee shall report to the MSSC. The Tenure, Promotion, and Reappointment Committee, the Computing Facilities Committee, and the Administrative Committee report directly to the School Director. Other committees may report to the School Director, the MSSC, or the Faculty as determined by the School Director.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- removed Division TPR Committees, Lecture Advisory Committee, and Post Tenure and Special Faculty Review Committees.  These will become sub-committees under TPR Committee. 
- changed name of Administrative Committee (to Administrative Council) and Computing Facilities Committee (to Computing Resources Committee)
- eliminated Curriculum Committee and moved curriculum matters to Undergraduate and Graduate affairs committees (see below)
-added ability of faculty to add Ad Hoc Committees
- added statement about selection by April 15 and one year renewable appointments as this was a section deleted from another Article incorporated into the language.  
</details>


### Section 1: Administrative Council

The Administrative Council, defined in Article III, Section 1, shall be chaired by the School Director and shall advise the School Director on scheduling of courses, budget, workload, and other administrative matters.

### Section 2: Computing Facilities Committee 

The Computing Facilities Committee shall advise the School Director on the purchase, disposition, and allocation of computing resources within the School. A member of this committee shall be appointed by the School Director to serve as the School’s representative to the College’s Computer Resources Committee.

### Section 3: Undergraduate Affairs and Curriculum Committee

The Undergraduate Affairs and Curriculum Committee shall include one representative from each of the subfaculties across all divisions. The Assistant Director for Undergraduate Affairs shall serve as an ex-officio voting member of the committee.  The Committee shall elect a chair of the Committee who shall serve as the representative on the College Undergraduate Curriculum Committee.  The Committee shall advise the MSSC on undergraduate curricula and other matters, including awards, pertaining to the undergraduate program. Other duties may be assigned by the School Director. Generally, the Committee’s agenda shall be made available to the Faculty at least one calendar day prior to its meetings. The committee may appoint subcommittees, not necessarily from its own members, as needed. Any such subcommittee shall report to the Committee. A subcommittee of undergraduate student advisors shall be a standing subcommittee, whose activities shall be coordinated by the Assistant Director for Undergraduate Affairs.

<details>
<summary> __Old Version__ </summary>
The Undergraduate Affairs Committee shall be chaired by the Associate Director for Undergraduate Studies and shall include one representative from each of the subfaculties across all divisions. It shall advise the MSSC on undergraduate curricula and other matters pertaining to the undergraduate program. Other duties may be assigned by the School Director. Generally, the Committee’s agenda will be made available to the Faculty one week prior to its meetings. The committee may appoint subcommittees, not necessarily from its own members, as needed. Any such subcommittee shall report to the Committee. A subcommittee of undergraduate student advisors shall be a standing subcommittee, whose activities shall be coordinated by the Associate Director for Undergraduate Affairs.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- The Faculty Manual requires that faculty representatives serving on University and College committees be elected faculty members. Currently, in order to satisfy this requirement, the School’s Curriculum Committee is defined to be all members of both the Graduate and Undergraduate Affairs Committees. A nominal “election” of the Chair of the Curriculum Committee is then held with the Undergraduate Coordinator being elected Chair. Currently changes to the Undergraduate curricula (or the Graduate curricula) are proposed, discussed and voted on in the Undergraduate Affairs (or the Graduate Affairs) Committee. These changes are then re-proposed discussed and voted on in the Curriculum Committee before advancing out of the School. The proposed change would eliminate the redundancy of curricula changes (after having passed the Undergraduate or Graduate Affairs Committee) having to go through a separate Curriculum Committee.
- In practice the hope is that the Assistant Director of Undergraduate Affairs serve as the chair of the Committee but that is not required.  
</details>

### Section 4: Graduate Affairs and Curriculum Committee 

The Graduate Affairs and Curriculum Committee shall include one representative, with graduate faculty status, from each subfaculty. The Assistant Director for Graduate Affairs shall serve as an ex-officio voting member of the committee.  The Committee shall elect a chair of the Committee and the representative on the College Graduate Curriculum Committee.  The Committee shall advise the MSSC on graduate curricula and other matters, including assistantships and awards, pertaining to the graduate program. Other duties may be assigned by the School Director. Generally, the Committee’s agenda shall be made available to the Faculty at least one calendar day prior to its meetings. The committee may appoint subcommittees, not necessarily from its own members, as needed. Any such subcommittee shall report to the Committee. A subcommittee of advisors for entering graduate students shall be a standing subcommittee, whose activities shall be coordinated by the Assistant Director for Graduate Affairs.

<details>
<summary> __Old Version__ </summary>
The Graduate Affairs Committee shall be chaired by the Associate Director for Graduate Studies and shall include one representative from the Mathematics and Statistics Education Division and from each subfaculty in the Mathematics and Statistics and Operations Research Divisions. It shall advise the MSSC on graduate curricula and other matters, including assistantships and awards, pertaining to the graduate program. Other duties may be assigned by the School Director. Generally, the Committee’s agenda will be made available to the Faculty one week prior to its meetings. The committee may appoint subcommittees, not necessarily from its own members, as needed. Any such subcommittee shall report to the Committee. A subcommittee of advisors for entering graduate students shall be a standing subcommittee, whose activities shall be coordinated by the Associate Director for Graduate Studies.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- The Faculty Manual requires that faculty representatives serving on University and College committees be elected faculty members. Currently, in order to satisfy this requirement, the School’s Curriculum Committee is defined to be all members of both the Graduate and Undergraduate Affairs Committees. A nominal “election” of the Chair of the Curriculum Committee is then held with the Undergraduate Coordinator being elected Chair. Currently changes to the Undergraduate curricula (or the Graduate curricula) are proposed, discussed and voted on in the Undergraduate Affairs (or the Graduate Affairs) Committee. These changes are then re-proposed discussed and voted on in the Curriculum Committee before advancing out of the School. The proposed change would eliminate the redundancy of curricula changes (after having passed the Undergraduate or Graduate Affairs Committee) having to go through a separate Curriculum Committee.
- In practice the hope is that the Assistant Director of Graduate Studies serve as the chair of the Committee but that is not required.
</details>

### Section 5: Research and Development Committee

The Research and Development Committee endeavors to foster research, development, and outreach activities of the School. It is responsible for organizing a program of colloquium speakers, conserving and trying to increase resources available for research and faculty development, and providing information to the scholarly community about the research activities of the School. The committee is also responsible for assisting the School Director in development activities and alumni relations. The Associate Directors of the Mathematics and Statistics and Operations Research Divisions shall be co-chairs of this committee.  Each subfaculty shall elect a member to the Research and Development Committee. The committee may appoint subcommittees, not necessarily from its own members, as needed. Any such subcommittee shall report to the Committee.

<details>
<summary> __Old Version__ </summary>
The Research and Development Committee endeavors to foster research, development, and outreach activities of the School. It is responsible for organizing a program of colloquium speakers, conserving and trying to increase resources available for research and faculty development, and providing information to the scholarly community about the research activities of the School. The committee is also responsible for assisting the School Director in development activities and alumni relations. The leaders of the Mathematics and Statistics and Operations Research Divisions shall be co-chairs of this committee.  Each subfaculty from those two divisions shall elect a member to the Research and Development Committee. The Mathematics and Statistics Education Division shall elect one representative. The committee may appoint subcommittees, not necessarily from its own members, as needed. Any such subcommittee shall report to the Committee.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- changing "leaders" to Associate Directors
- made all subfaculties have equal representation on committee
</details>


### Section 6: Tenure, Promotion and Reappointment (TPR) Committee

The TPR Committee shall serve as the School’s evaluation committee in matters related to appointment, reappointment, promotion, tenure, post tenure, and graduate faculty status review of all faculty with or pursing appointments within the School. The procedures and criteria for Post-Tenure Review, Tenure, Promotion, and Reappointment may be found in the department’s separate TPR document. The committee may also be involved in additional personnel matters as deemed appropriate by the Director to provide input into personnel decisions including, but not limited to, meritorious compensation, disciplinary action, or conflict resolution. The committee shall meet as often as necessary to accomplish this charge.

<details>
<summary> __Old Version__ </summary>
Section 7. Divisions containing voting faculty who are also regular faculty shall each have their own Tenure, Promotion, and Reappointment Committee. The creation and function of each committee shall be in accordance with the Guidelines for Tenure, Promotion, and Reappointment for the School of Mathematical and Statistical Sciences.

Section 8. The Lecturer Advisory Committee will consist of six lecturers who hold the rank of senior lecturer or higher. Its creation and function shall be in accordance with the Guidelines for Tenure, Promotion and Reappointment for the School of Mathematical and Statistical Sciences.

Section 9. The Post Tenure and Special Faculty (PTSF) review Committee shall be determined and function in accordance with the Guidelines for Tenure, Promotion, and Reappointment for the School of Mathematical and Statistical Sciences.

</details>

<details>
<summary> __Explanation of Changes__ </summary>
The new TPR document will combine these committee into one TPR Committee with sub-committees.  
</details>

***

## Article IX Representatives

### Section 1: College/University Committee Representatives 

Elections of Faculty representatives to various college or university organizations shall either occur at a meeting of the Faculty or by mail or electronic ballot. Nominations are accepted from the Voting Faculty. The timeline and process for electing representation for College level and University committees shall be conducted according to the College of Science bylaws. 

<details>
<summary> __Old Version__ </summary>
Elections of Faculty representatives to various college or university organizations shall either occur at a meeting of the Faculty or by mail or electronic ballot. Nominations are accepted from the Voting Faculty. Elections for alternates shall be conducted separately.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- new election procedures outlined in the COS bylaws  
</details>

### Section 2:  Replacement of Unexpired Term

A replacement for the unexpired term of any representative to the MSSC, college or university organization, or School committee who is unable to complete a term shall be appointed by the Director. The replacement takes office immediately upon selection.



<details>
<summary> __Old Version__ </summary>
A replacement for the unexpired term of any representative to the MSSC, college or university organization, or School committee who is unable to complete a term shall be selected as soon as possible, using the same rules as the original selection. The replacement takes office immediately upon selection.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- update to comply with practice
</details>

***

## Article X: Hiring of Faculty

### Section 1: Regular Appointments

To fill a regular appointment faculty position, the Director in consultation with the Associate Directors, shall appoint a Search Committee consisting primarily of members of subfaculties directly related to the area of the candidate, who shall conduct the search in accordance with the Clemson University Faculty Manual. Members of the Search Committee shall be from at least two different subfaculties, and be composed in accordance with College of Science and University guidelines. This will normally mean that at least one member of the Search Committee will be from a subfaculty that differs from the primary area specified for the candidate. The Search Committee shall invite feedback from all faculty members of the School to discuss the relative merits of the final candidates. Outcomes of this process will be considered by the Search Committee in its final deliberation and shall be presented to the Assciate Directors and the Director; the Associate Directors shall advise the Director in making the selection.


<details>
<summary> __Old Version__ </summary>
Section 1. To fill a tenured or tenure-track faculty position, a Division Leader, with input from the School Director, will appoint a Search Committee consisting primarily of members of subfaculties directly related to the area of the candidate, who will conduct the search in accordance with the Clemson University Faculty Manual. Members of the Search Committee shall be from at least two different subfaculties, and be composed in accordance with College of Science and University guidelines. This will normally mean that at least one member of the Search Committee will be from a subfaculty that differs from the primary area specified for the candidate. The Search Committee will invite feedback from all faculty members of the School to discuss the relative merits of the final candidates. It will also conduct a vote of the respective Division Faculty on candidate preferences and candidate acceptability/unacceptability. Both qualitative and quantitative outcomes of this process will be considered by the Search Committee in its final deliberation and will be presented to the Division Leader and the Director; the Division Leader will advise the Director in making the selection.
<br>
Section 2.  Search committees for lecturers, including a designated chair, shall be appointed by the School Director, with advice from Division Leaders and the MSSC. The search committee, consisting of three members, shall make a recommendation to the Director.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- In order for consistency across all disciplines we recommend the search committee process be conducted for all regular faculty appointments.  
</details>

### Section 2: Special Appointments

In the case of an appointment to a faculty position not described here (e.g. postdoctoral research fellow, temporary faculty, or research faculty), the School Director in consultation with the Associate Directors and, if applicable, the sponsoring regular faculty member, shall consult with the MSSC regarding the appointee.  At the discretion of the Director a search committee may be formed to evaluate candidates.  

<details>
<summary> __Old Version__ </summary>
In the case of an appointment to a faculty position not described here (e.g. postdoctoral research fellow or research faculty), the School Director and, if applicable, the sponsoring regular faculty member, will consult with the MSSC regarding the appointee’s qualifications.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- Edited to comply with current practices
</details>

***

## Article XI: Amendments

### Section 1: Amendments to Bylaws

The Bylaws can be amended by the Voting Faculty, either at a meeting of the Faculty or electronic ballot, provided the amendment has been distributed to each member at least two weeks in advance of the voting. Passage requires support by 51% of the Voting Faculty or 2/3 of the votes cast, whichever count is larger.

<details>
<summary> __Old Version__ </summary>
The Bylaws can be amended by the Voting Faculty, either at a meeting of the Faculty or by mail or electronic ballot, provided the amendment has been distributed to each member at least two weeks in advance of the voting. Passage requires support by 51% of the Voting Faculty or 2/3 of the votes cast, whichever count is larger.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- removed "by mail"
</details>

### Section 2: TPR Guidelines

The Guidelines for Tenure, Promotion and Reappointment and Post Tenure Review Guidelines for the School of Mathematical and Statistical Sciences can be amended at the request of a member of the Tenure, Promotion, and Reappointment Committee and subject to ratification by the regular faculty. Amendments approved by a majority vote of the combined voting membership of the Tenure, Promotion, and Reappointment Committees shall be distributed to each member of the regular faculty at least two weeks in advance of the vote for ratification. Support by 51% of the combined voting membership or 2/3 of the votes cast, whichever count is larger, is required for ratification. Voting may be either at a meeting or electronic ballot.

<details>
<summary> __Old Version__ </summary>
The Guidelines for Tenure, Promotion and Reappointment for the School of Mathematical and Statistical Sciences can be amended at the request of a member of either Division’s Tenure, Promotion, and Reappointment Committee subject to ratification by the regular faculty. Amendments approved by a majority vote of the combined voting membership of the two Tenure, Promotion, and Reappointment Committees will be distributed to each member of the regular faculty at least two weeks in advance of the vote for ratification. Support by 51% of the combined voting membership or 2/3 of the votes cast, whichever count is larger, is required for ratification. Voting may be either at a meeting or by mail or electronic ballot.
</details>

<details>
<summary> __Explanation of Changes__ </summary>
- changed language for one TPR committee rather than 2
- removed "by mail"
- combined TPR and Post Tenure Review Guideline amendments 
</details>

***

## Article XII: Parlimentary Authority

The rules contained in the current edition of Robert’s Rules of Order Newly Revised shall govern this assembly in all cases to which they are applicable and in which they are not inconsistent with these bylaws, the College bylaws, the Faculty Manual, the Constitution of the Faculty of Clemson University, and any special rules of order the faculty may adopt.


<details>
<summary> __Explanation of Changes__ </summary>
- new section designating that Parlimentary Authority unless otherwise specified.  
</details>
